tabs:
  main:
    display: Main
    sections:
      -
        fields:
          -
            handle: collections
            field:
              type: collections
              display: Collections
              width: 50
              mode: select
              default: events
          -
            handle: timezone
            field:
              dictionary: timezones
              max_items: 1
              type: dictionary
              display: Timezone
              default: computed:default-events-timezone
              width: 50
