name: Release Drafter

on:
  pull_request:
    types: [closed]

jobs:
  draft:
    uses: edalzell/github-workflows/.github/workflows/release-draft.yml@5ebfc6714a6c4ca7f2434ff01736ea2405e1c323 # v1.3.1
    permissions:
      contents: write
      pull-requests: write
