name: PR Labeler

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  label:
    uses: edalzell/github-workflows/.github/workflows/label-pr.yml@d3f1ca37a5377c14d34fc54320cc8d8141badfe5 # v1.5.0
    permissions:
      contents: read
      pull-requests: write
