name: PR Labeler

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  label:
    uses: edalzell/github-workflows/.github/workflows/label-pr.yml@9f72f0b77303abff9903b16da75346b1eb1c3785 # v1.4.0
    permissions:
      contents: read
      pull-requests: write
