name: Release Publish

on:
  pull_request:
    types: [closed]

jobs:
  publish:
    uses: edalzell/github-workflows/.github/workflows/release-publish.yml@d3f1ca37a5377c14d34fc54320cc8d8141badfe5 # v1.5.0
    permissions:
      contents: write
