name: Release Publish

on:
  pull_request:
    types: [closed]

jobs:
  publish:
    uses: edalzell/github-workflows/.github/workflows/release-publish.yml@9f72f0b77303abff9903b16da75346b1eb1c3785 # v1.4.0
    permissions:
      contents: write
