name: "Update Changelog"

on:
  release:
    types: [published]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Update Changelog
        id: update_changelog
        uses: stefanzweifel/changelog-updater-action@v1
        with:
          latest-version: ${{ github.ref_name }}
          release-notes: ${{ github.event.body }}
      - name: Commit updated CHANGELOG
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: main
          commit_message: Update CHANGELOG
          file_pattern: CHANGELOG.md
